# Generated by Django 3.1.4 on 2020-12-19 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_auto_20201218_2320'),
        ('documentos', '0002_documento_dono_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='dono_documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='colaboradores.colaborador'),
            preserve_default=False,
        ),
    ]
